#!/usr/bin/env node
/* Generates the power sound cues in assets/sfx/ with ElevenLabs.
   Usage: ELEVENLABS_API_KEY=... node tools/elevenlabs-sfx.mjs [cue ...]
   The key is read from the environment only. Never commit it: the site is public.
   Voice lines use ElevenLabs stock voices, not clones of real voice actors. */
import { writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const KEY = process.env.ELEVENLABS_API_KEY;
if (!KEY) { console.error('Set ELEVENLABS_API_KEY'); process.exit(1); }
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'sfx');
const API = 'https://api.elevenlabs.io/v1';
const MALE = 'pNInz6obpgDQGcFmaJgB';   // stock "Adam", deep male
const YOUNG = 'TxGEqnHWrfWFTfGW9XAX';  // stock "Josh", young male

const SFX = {
  chidori_charge: ['Crackling blue lightning held in a hand, thousands of chirping birds, high-pitched electric screech building in intensity, anime sound effect', 2.4],
  chidori_hit: ['Massive lightning strike impact, glass shattering, deep boom with electric crackle tail, anime impact', 2.2],
  arise_drone: ['Dark ominous low drone, deep sub bass swell, whispering shadows, eerie dark fantasy atmosphere', 4],
  arise_souls: ['Ghostly souls being ripped out of bodies, dark whooshes, spectral wails, black smoke rising', 3],
  arise_rise: ['Army of shadow soldiers rising from the ground, dark energy surge, deep rumble and metallic armor clank', 3],
  arise_done: ['Dark magic seal locking with deep resonant boom and reverb tail', 2],
  wind_gust: ['Powerful gust of wind sweeping past, leaves and fabric flapping, anime wind whoosh', 2.5],
  kame_charge: ['Energy ball charging in cupped hands, rising hum, crackling blue energy, anime ki charge', 3.5],
  kame_fire: ['Huge energy beam firing, roaring blast with rumbling bass and sizzling energy, anime beam attack', 3.5],
  slash_breath: ['Sharp controlled breath inhale, then a sword being unsheathed with metallic ring', 1.5],
  slash_fire: ['Roaring flame swirl like a fire dragon, whooshing blaze, anime fire sword technique', 2.5],
  slash_cut: ['Single devastating katana slash, sharp whoosh and blade ring, fiery impact burst', 1.6],
  ssj_scream: ['Golden aura powering up, crackling electricity, rising roar of energy, ground rumbling, anime transformation', 4],
};
const VOICE = {
  arise_voice: [MALE, 'Arise.', { stability: .35, similarity_boost: .8, style: .7 }],
  kame_ka: [YOUNG, 'Ka...', { stability: .3, style: .8 }],
  kame_me: [YOUNG, 'me...', { stability: .3, style: .8 }],
  kame_ha: [YOUNG, 'ha...', { stability: .3, style: .8 }],
  kame_me2: [YOUNG, 'me...!', { stability: .3, style: .9 }],
  kame_haaa: [YOUNG, 'HAAAAAAAA!', { stability: .2, style: 1 }],
  slash_voice: [YOUNG, 'Hinokami Kagura!', { stability: .3, style: .9 }],
  ssj_voice: [YOUNG, 'AAAAAAAAHHH!', { stability: .2, style: 1 }],
};

async function post(path, body) {
  const r = await fetch(API + path, { method: 'POST', headers: { 'xi-api-key': KEY, 'Content-Type': 'application/json', Accept: 'audio/mpeg' }, body: JSON.stringify(body) });
  if (!r.ok) throw new Error(path.split('/').slice(0, 3).join('/') + ' ' + r.status + ' ' + (await r.text()).slice(0, 200));
  return Buffer.from(await r.arrayBuffer());
}

const want = process.argv.slice(2);
const pick = (n) => !want.length || want.includes(n);
for (const [name, [text, dur]] of Object.entries(SFX)) {
  if (!pick(name)) continue;
  try { writeFileSync(join(OUT, name + '.mp3'), await post('/sound-generation', { text, duration_seconds: dur, prompt_influence: .5 })); console.log('ok', name); }
  catch (e) { console.error('fail', name, e.message); }
}
for (const [name, [voice, text, settings]] of Object.entries(VOICE)) {
  if (!pick(name)) continue;
  try { writeFileSync(join(OUT, name + '.mp3'), await post('/text-to-speech/' + voice + '?output_format=mp3_44100_128', { text, model_id: 'eleven_multilingual_v2', voice_settings: { similarity_boost: .75, ...settings } })); console.log('ok', name); }
  catch (e) { console.error('fail', name, e.message); }
}

const files = {};
for (const f of readdirSync(OUT).sort()) if (f.endsWith('.mp3')) files[f.slice(0, -4)] = f;
writeFileSync(join(OUT, 'sounds.js'), '/* Recorded power sound cues, generated by tools/elevenlabs-sfx.mjs.\n   Any cue missing here falls back to the synthesized sound in assets/js/powers.js. */\nwindow.XR_SFX = { files: ' + JSON.stringify(files, null, 2) + ' };\n');
console.log(Object.keys(files).length, 'cues in sounds.js');
