#!/usr/bin/env node
/*
  Cache-busting for CSS and JS.

  Adds ?v=<content hash> to every local stylesheet and script link in the pages,
  so a browser that cached an older file fetches the new one right after a deploy
  instead of pairing new HTML with old CSS/JS. Only files that changed get a new
  version. Safe to run again.

  Run it before every push that changes CSS or JS:  node tools/version-assets.js

  Scripts that load more files themselves pass their own ?v= on to them, so their
  version also covers those files (listed in DEPS below).
*/
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.resolve(__dirname, '..');
const SKIP = new Set(['.git', '.github', '.claude', 'tools', 'assets', 'node_modules']);

const list = dir => fs.readdirSync(path.join(root, dir)).map(f => path.posix.join(dir, f));
const DEPS = {
  'assets/js/powers.js': ['assets/css/powers.css', 'assets/sfx/sounds.js'],
  'assets/js/shop.js': [...list('assets/css/shop'), ...list('assets/js/shop')].sort(),
};

// power sounds: list the clips in assets/sfx/ (each with its own ?v=) for powers.js
const AUDIO = /\.(mp3|m4a|aac|ogg|oga|opus|wav|webm)$/i;
const sfxFiles = fs.readdirSync(path.join(root, 'assets/sfx')).filter(f => AUDIO.test(f)).sort();
const sfxList = sfxFiles.map(f => {
  const v = crypto.createHash('sha1').update(fs.readFileSync(path.join(root, 'assets/sfx', f))).digest('hex').slice(0, 8);
  return `  ${JSON.stringify(f.replace(AUDIO, ''))}: ${JSON.stringify(`${encodeURI(f)}?v=${v}`)}`;
});
// the cue sheet: timings inside the clips (seconds) that the powers sync their visuals to
const marksPath = path.join(root, 'assets/sfx/marks.json');
const marks = fs.existsSync(marksPath) ? JSON.parse(fs.readFileSync(marksPath, 'utf8')) : {};
fs.writeFileSync(path.join(root, 'assets/sfx/sounds.js'),
  '/* Power sound clips found in assets/sfx/, and their cue marks from assets/sfx/marks.json.\n' +
  '   Generated by tools/version-assets.js: do not edit. Cue names are listed at the top of\n' +
  '   the SOUND section in assets/js/powers.js. */\n' +
  `window.XR_SFX = { files: {${sfxList.length ? '\n' + sfxList.join(',\n') + '\n' : ''}}, marks: ${JSON.stringify(marks)} };\n`);
console.log(`${sfxFiles.length} power sound clip(s) listed in assets/sfx/sounds.js.`);

// images written with ?v= anywhere in the pages, scripts or stylesheets (for example
// assets/img/og-cover.jpg?v=0) get the hash of the image itself, so a replaced picture is
// fetched fresh even by a browser that cached the old one. Runs before the CSS/JS hashes,
// since it can change those files.
const IMG = /((?:\.\.\/)*assets\/img\/[^"'()?#\s]+\.(?:jpe?g|png|webp|avif|gif|svg))\?v=[0-9a-f]*/g;
function imgFiles(dir, out) {
  for (const e of fs.readdirSync(path.join(root, dir), { withFileTypes: true })) {
    const rel = path.posix.join(dir, e.name);
    if (e.isDirectory()) { if (!['.git', '.github', '.claude', 'tools', 'node_modules', 'img', 'sfx'].includes(e.name)) imgFiles(rel, out); }
    else if (/\.(html|js|css)$/.test(e.name)) out.push(rel);
  }
  return out;
}
let imgRefs = 0;
for (const f of imgFiles('.', [])) {
  const src = fs.readFileSync(path.join(root, f), 'utf8');
  const out = src.replace(IMG, (m, url) => {
    const file = path.join(root, url.replace(/^(\.\.\/)+/, ''));
    if (!fs.existsSync(file)) { console.warn(`  missing image: ${url} (in ${f})`); return m; }
    imgRefs++;
    return url + '?v=' + crypto.createHash('md5').update(fs.readFileSync(file)).digest('hex').slice(0, 8);
  });
  if (out !== src) { fs.writeFileSync(path.join(root, f), out); console.log(`  image versions in ${f}`); }
}
if (imgRefs) console.log(`${imgRefs} versioned image reference(s) checked.`);

// line endings are normalised so Windows and Linux checkouts give the same hash
const text = f => fs.readFileSync(path.join(root, f), 'utf8').replace(/\r\n/g, '\n');
const hashes = {};
function version(f) {
  if (!hashes[f]) {
    const h = crypto.createHash('sha1');
    for (const x of [f, ...(DEPS[f] || [])]) h.update(x + '\0' + text(x) + '\0');
    hashes[f] = h.digest('hex').slice(0, 8);
  }
  return hashes[f];
}

function pages(dir, out) {
  for (const e of fs.readdirSync(path.join(root, dir), { withFileTypes: true })) {
    const rel = path.posix.join(dir, e.name);
    if (e.isDirectory()) { if (!SKIP.has(e.name) && !e.name.startsWith('.')) pages(rel, out); }
    else if (e.name.endsWith('.html')) out.push(rel);
  }
  return out;
}

const LINK = /((?:href|src)=")((?:\.\.\/)*assets\/[^"?#]+\.(?:css|js))(?:\?v=[0-9a-f]*)?"/g;
let changed = 0;
for (const page of pages('.', [])) {
  const src = fs.readFileSync(path.join(root, page), 'utf8');
  const out = src.replace(LINK, (m, attr, url) => {
    const file = path.posix.normalize(path.posix.join(path.posix.dirname(page), url));
    if (!fs.existsSync(path.join(root, file))) { console.warn(`  missing: ${file} (in ${page})`); return m; }
    return `${attr}${url}?v=${version(file)}"`;
  });
  if (out !== src) { fs.writeFileSync(path.join(root, page), out); changed++; console.log(`  updated ${page}`); }
}
console.log(`${changed} page(s) updated, ${Object.keys(hashes).length} CSS/JS files versioned.`);
